{
	"version": 1697659181,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/หญ้า-sheet0.png",
		"images/sprite-sheet0.png",
		"images/ground-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/enemy01-sheet0.png",
		"images/enemy01-sheet1.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/fs.png",
		"images/เหรียญ-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/restart-sheet0.png",
		"images/wall-sheet0.png",
		"images/ดินเลื่อน-sheet0.png",
		"images/ดินเอียง-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/enemy02-sheet0.png",
		"images/enemy02-sheet1.png",
		"images/หน้าเมนูเกม-sheet0.png",
		"images/เส้นชัย-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite16-sheet0.png",
		"media/cartoon-jump-6462 (online-audio-converter.com).ogg",
		"media/sound-effect-twinklesparkle-115095 (online-audio-converter.com).ogg",
		"media/8bit-music-for-game-68698 (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}